### ISSUE TITLE
Missing unbzip2-stream.min.js

### ISSUE THREAD

**Issue by sfriesel** [regular/unbzip2-stream#36]
The UMD file `dist/unbzip2-stream.min.js` is missing since version 1.4.0.

https://unpkg.com/browse/unbzip2-stream@1.3.3/dist/
https://unpkg.com/browse/unbzip2-stream@1.4.2/dist/

**Comment by regular** [comment]
ha, not sure if this ever was a problem for anyone :) I'd accept a PR that builds it via pre-publish script, though, if someone wants to procrastinate.

**Comment by sfriesel** [comment]
The readme advertises this as a feature/use case:

> <script src="https://npm-cdn.info/unbzip2-stream/dist/unbzip2-stream.min.js"></script>

`prepublish` has been deprecated since npm4 in favor of `prepare`. There already is a `prepare` script which generates the file. Not sure how it did not end up in the releases.

**Comment by regular** [comment]
hmm, I see. Maybe I used a very old version of npm to publish. Thanks for bringing this up!

**Comment by regular** [comment]
Yes, that seems to have been the problem.
I published using npm 6.14.5 and now it's back:
https://unpkg.com/browse/unbzip2-stream@1.4.3/dist/
