### ISSUE TITLE
Tests missing 'fixture' file

### ISSUE THREAD

**Issue by tedbrandston** [regular/unbzip2-stream#5]
You've left out the vmlinux file, which makes sense because it's big but means that I can't run all of the tests. 
I also don't see anything that's supposed to download it for me.

**Comment by regular** [comment]
Hi @tedbrandston, please refer to the end of the readme file.

**Comment by regular** [comment]
Ok, the download mentioned in the readme no longer works. I did this instead:
``` sh
dd if=/dev/urandom of=test/fixtures/vmlinux.bin bs=5m count=2
cat test/fixtures/vmlinux.bin | bzip2 > test/fixtures/vmlinux.bin.bz2
```
